version: '3.9'

services:
  client1:
    restart: always
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - .:/app  
    env_file:
      - internal/config/envs/.env.dev
    ports:
      - "2222:8888"

  # client2:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: api.Dockerfile
  #   volumes:
  #     - .:/app  
  #   env_file:
  #     - internal/config/envs/.env.prod
  #   ports:
  #     - "8080:1111"