version: '3.9'

services:

  app:
    container_name: ai-bot-app
    restart: always
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  postgresql:
    container_name: ai-bot-db
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    volumes:
      - pstg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432

  # migration:
  #   build:
  #     context: ./docker/db-migrate/
  #     dockerfile: Dockerfile
  #   command: >
      
  #   volumes:
  #   #   - ./migrations/:/migration/migrations
  #   depends_on:
  #     - postgresql
    


volumes:
  pstg: