version: '3.9'

services:

  app:
    image: ai-assistant-app
    container_name: backend-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - MODE=${MODE}
      - API_KEY=${API_KEY}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    networks:
      - ps
    mem_limit: 1560m
    logging:
      driver: "json-file"
      options:
        max-size: "400m"
        max-file: "10"
    

  postgresql:
    container_name: db
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    volumes:
      - pstg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - ps
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # migration:
  #   build:
  #     context: ./docker/db-migrate/
  #     dockerfile: Dockerfile
  #   command: >
      
  #   volumes:
  #   #   - ./migrations/:/migration/migrations
  #   depends_on:
  #     - postgresql


networks:
  ps:

volumes:
  pstg: