version: '3.8'

services:
  app:
    container_name: messages_handler
    restart: always
    volumes:
      - ./config.yml:/app/config.yml
    ports:
      - 8888:8888
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - AUTH_TOKEN=${AUTH_TOKEN}
    env_file:
      - .env