version: '3.9'

services:
  app:
    container_name: messages_handler
    restart: always
    build:
      dockerfile: api.Dockerfile
    volumes:
      - ./config.yml:/app/config.yml
    ports:
      - 8888:8888
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
    env_file:
      - .env